name: direct
channels:
  - defaults
dependencies:
  - matplotlib=2.2
  - nb_conda
  - numpy=1.15
  - pandas
  - pip=10.0
  - python=3.6
  - scikit-learn=0.19
  - scipy=1.1
  - pip:
    - tensorflow==1.10.0

